# Generated by Django 3.2.23 on 2023-12-03 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0005_card_user_skips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст')),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка от 1 до 5')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='card.card', verbose_name='Карточка')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onme_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о пользователе',
                'verbose_name_plural': 'Отзывы о пользователе',
            },
        ),
    ]
