# Generated by Django 3.2.23 on 2023-12-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='card',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
