# Generated by Django 3.2.22 on 2023-11-05 14:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Возможны только 6 цифр от 0 до 9', regex='^\\d{6}$')], verbose_name='Код')),
                ('expiration_date', models.DateTimeField(verbose_name='Срок годности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Код для авторизации',
                'verbose_name_plural': 'Коды для авторизации',
            },
        ),
    ]
