# Generated by Django 3.2.23 on 2023-11-08 11:37
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20231106_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datetime_consent_to_processing_of_personal_data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now(), verbose_name='Дата и время согласия пользователя на обработку персональных данных'),
            preserve_default=False,
        ),
    ]
