# Generated by Django 3.2.23 on 2023-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_datetime_consent_to_processing_of_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_consent_to_processing_of_personal_data',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время согласия пользователя на обработку персональных данных'),
        ),
    ]
