# Generated by Django 3.2.23 on 2023-11-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('user', '0006_alter_user_datetime_consent_to_processing_of_personal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city', verbose_name='Город'),
        ),
    ]
