# Generated by Django 3.2.23 on 2023-11-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20231122_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('looking_for', 'В поиске сожителя'), ('not_looking_for_anyone', 'Никого не ищу')], max_length=100, verbose_name='Статус')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ссылка на соц. сеть',
                'verbose_name_plural': 'Ссылки на соц. сеть',
            },
        ),
    ]
