# Generated by Django 3.2.23 on 2023-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usersociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersociallink',
            name='type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('vk', 'Вконтакте'), ('facebook', 'Facebook')], max_length=100, verbose_name='Статус'),
        ),
    ]
