# Generated by Django 3.2.23 on 2023-11-23 13:08

import apps.user.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usersociallink_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_preview',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.User.upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])], verbose_name='Аватарка-превью'),
        ),
    ]
