# Generated by Django 3.2.23 on 2023-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_avatar_preview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersociallink',
            unique_together={('user', 'type')},
        ),
    ]
