# Generated by Django 3.2.23 on 2023-11-22 11:36

import apps.card.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=2048, verbose_name='Описание')),
                ('limit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество сожителей')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateField(default=None, null=True, verbose_name='Крайний срок')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('draft', 'Черновик'), ('completed', 'Завершено')], default='active', max_length=100, verbose_name='Статус')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='city.city', verbose_name='Город')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Символьный код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Тег карточки',
                'verbose_name_plural': 'Теги карточки',
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=100, verbose_name='Статус')),
                ('roommates_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество предлагаемых сожителей')),
                ('covering_letter', models.CharField(blank=True, max_length=2048, verbose_name='Сопроводительное письмо')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='card.card', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на карточку',
                'verbose_name_plural': 'Заявки на карточку',
            },
        ),
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.card.models.CardPhoto.upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])], verbose_name='Фото')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='card.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Фото карточки',
                'verbose_name_plural': 'Фотки карточки',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(to='card.CardTag', verbose_name='Теги'),
        ),
    ]
