# Generated by Django 3.2.23 on 2023-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', to='card.CardTag', verbose_name='Теги'),
        ),
    ]
