# Generated by Django 3.2.23 on 2023-11-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtag',
            name='code',
        ),
    ]
