# Generated by Django 3.2.23 on 2023-11-26 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_cardtag_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Максимальное количество сожителей'),
        ),
    ]
