# Generated by Django 3.2.23 on 2023-12-02 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0004_alter_card_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user_skips',
            field=models.ManyToManyField(related_name='card_skips', to=settings.AUTH_USER_MODEL, verbose_name='Пропуски пользователя'),
        ),
    ]
